### ISSUE TITLE
Video Playing Automatically

### ISSUE THREAD

**Issue by jlag34** [gregorysgeorge/capstoneproject#3]
Looking at it from a user perspective, you might want to turn off the autoplay on your video. If the video was a large video (size wise) it would slow down the performance of the website while loading. Also, it takes away from what else is going on. All the attention is towards the video rather than the page itself. Lastly, giving the user the decision to start the video or not seems like the right path to me. Maybe they aren’t interested in watching or it autoplaying distracts them away from something else they were doing. Just playing devil’s advocate and get you thinking.

**Comment by gregorysgeorge** [comment]
You're right. I totally agree with you... I'm going to change it.
