### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [gregorysgeorge/capstoneproject#5]
You did a really great job with this project. The responsiveness is on point and the page layout looks good no matter the size of the screen. The extra effort you put into the CSS makes the page pop and gives a feel of professionalism. Looking into UX (user experience), think user first. There is no right answer to the video autoplaying but it is something to think about. Lastly, maybe think about moving to 2 spaces per indent. Again, really great job.

**Comment by gregorysgeorge** [comment]
Thank you again for your review and your suggestions.
